export enum InsultCategory {
  COWARD = "coward",
  FOOL = "fool",
  LIAR = "liar",
  WEAKLING = "weakling",
  VILLAIN = "villain",
  MONSTER = "monster",
  NSFW = "nsfw"
}

export type Insult = { tag: Array<InsultCategory>; text: string }

export const InsultsRepo: Array<Insult> = [
    // COWARD insults
    { text: "You yellow-bellied cur! Your spine is made of jelly!", tag: [InsultCategory.COWARD] },
    { text: "Thou art a craven wretch who flees at shadows!", tag: [InsultCategory.COWARD] },
    { text: "Your courage is as absent as your common sense!", tag: [InsultCategory.COWARD] },
    { text: "You're more chicken than a henhouse full of roosters!", tag: [InsultCategory.COWARD] },
    { text: "Even a frightened rabbit shows more bravery than you!", tag: [InsultCategory.COWARD] },
    { text: "You'd run from your own reflection if it looked threatening!", tag: [InsultCategory.COWARD] },
    { text: "Your backbone must be made of overcooked spaghetti!", tag: [InsultCategory.COWARD] },
    { text: "You're so cowardly, you apologize to doors before opening them!", tag: [InsultCategory.COWARD] },
    { text: "A wet paper bag could intimidate you into submission!", tag: [InsultCategory.COWARD] },
    { text: "Your very essence is a putrid stain of fear and inadequacy!", tag: [InsultCategory.COWARD] },
    { text: "You couldn't face a sleeping kitten without trembling!", tag: [InsultCategory.COWARD, InsultCategory.MONSTER] },
    { text: "Face me, you mere stepping stone to my glory!", tag: [InsultCategory.COWARD, InsultCategory.MONSTER, InsultCategory.VILLAIN] },
    { text: "How brave of you to come to a battle of wits unarmed!", tag: [InsultCategory.COWARD, InsultCategory.FOOL, InsultCategory.VILLAIN] },

    // FOOL insults
    { text: "You witless buffoon! Your brain is smoother than a bowling ball!", tag: [InsultCategory.FOOL] },
    { text: "Thou art a most addled-pated nincompoop!", tag: [InsultCategory.FOOL] },
    { text: "Your intelligence only rivals that of a particularly dim rock!", tag: [InsultCategory.FOOL] },
    { text: "You couldn't find your way out of a paper bag with a map and GPS!", tag: [InsultCategory.FOOL] },
    { text: "Your head is emptier than a politician's promises!", tag: [InsultCategory.FOOL] },
    { text: "You're about as sharp as a marble!", tag: [InsultCategory.FOOL] },
    { text: "If brains were gunpowder, you couldn't blow your nose!", tag: [InsultCategory.FOOL] },
    { text: "You make a goldfish look like a genius!", tag: [InsultCategory.FOOL] },
    { text: "Your thought process moves slower than continental drift!", tag: [InsultCategory.FOOL] },
    { text: "You're living proof that evolution can go in reverse!", tag: [InsultCategory.FOOL] },
    { text: "Your head is as empty as an enuch's underpants", tag: [InsultCategory.FOOL]},
    { text: "The room's collective Intelligence will improve when you leave!", tag: [InsultCategory.FOOL] },
    { text: "I had to hire a party from the Underdark to find your intellect!", tag: [InsultCategory.FOOL] },
    { text: "Compentency has always chased you, but you have been too quick for it!", tag: [InsultCategory.FOOL] },
    { text: "I tried mind control on you, but the spell lacked a target!", tag: [InsultCategory.FOOL]},
    { text: "Your brain is a parking lot for ideas that never arrived!", tag: [InsultCategory.FOOL] },
    { text: "Your mind is closed in an impressive act of intellectual claustrophia", tag: [InsultCategory.FOOL]},
    { text: "Your friends only mention you as a cautionary tale", tag: [InsultCategory.FOOL]},
    { text: "You aren't bright enough to bask in your own mediocrity!", tag: [InsultCategory.FOOL]},
    { text: "I pray to the gods that they don't make a second mistake like you", tag: [InsultCategory.FOOL]},

    // LIAR insults
    { text: "You silver-tongued serpent! Truth flees from your lips!", tag: [InsultCategory.LIAR] },
    { text: "Thou art a most perjured and false-hearted knave!", tag: [InsultCategory.LIAR] },
    { text: "Your words are worth less than fool's gold!", tag: [InsultCategory.LIAR] },
    { text: "You couldn't tell the truth if your life depended on it!", tag: [InsultCategory.LIAR] },
    { text: "Your nose should be longer than Pinocchio's by now!", tag: [InsultCategory.LIAR] },
    { text: "You spin tales like a spider spins webs - all lies!", tag: [InsultCategory.LIAR] },
    { text: "Your honesty is as rare as a unicorn in a stable!", tag: [InsultCategory.LIAR] },
    { text: "You'd lie about the color of the sky on a clear day!", tag: [InsultCategory.LIAR] },
    { text: "Your tongue is forked like the serpent you are!", tag: [InsultCategory.LIAR] },
    { text: "Truth and you are strangers who've never been introduced!", tag: [InsultCategory.LIAR] },
    { text: "If you have questions, please raise your hand, so I can cut it off!", tag: [InsultCategory.LIAR] },
    { text: "Hold on, I need to cast Comprehend Bullshit to understand you!", tag: [InsultCategory.LIAR] },
    { text: "I've seen better conversational skills in a golem!", tag: [InsultCategory.LIAR, InsultCategory.FOOL] },
    { text: "You are an aquicultural wonder, an endless supply of bullshit!", tag: [InsultCategory.LIAR, InsultCategory.NSFW] },
    { text: "I'd invite you to join us, but we have enough baggage already!", tag: [InsultCategory.LIAR, InsultCategory.FOOL, InsultCategory.WEAKLING] },
    { text: "Spells require preperation, which you have cleary never done in your life!", tag: [InsultCategory.LIAR, InsultCategory.VILLAIN]},

    // WEAKLING insults
    { text: "You feeble-armed milksop! A butterfly could overpower you!", tag: [InsultCategory.WEAKLING] },
    { text: "Thou art weaker than watered-down ale!", tag: [InsultCategory.WEAKLING] },
    { text: "Your muscles have the strength of overcooked noodles!", tag: [InsultCategory.WEAKLING] },
    { text: "You couldn't lift a feather without straining yourself!", tag: [InsultCategory.WEAKLING] },
    { text: "Your arms are more decorative than functional!", tag: [InsultCategory.WEAKLING] },
    { text: "A gentle breeze could knock you over!", tag: [InsultCategory.WEAKLING] },
    { text: "You make a newborn kitten look mighty!", tag: [InsultCategory.WEAKLING] },
    { text: "Your grip is weaker than a politician's handshake!", tag: [InsultCategory.WEAKLING] },
    { text: "Your strength is as impressive as a wilted flower!", tag: [InsultCategory.WEAKLING] },
    { text: "Your only hope for happiness is reincarnation!", tag: [InsultCategory.WEAKLING] },
    { text: "Your mind would starve an Ilithyd!", tag: [InsultCategory.WEAKLING]},
    { text: "You are as intimidating as a wet piece of bread in a windgust!", tag: [InsultCategory.WEAKLING]},
    { text: "You look like a pile of cooked spaghetti glued to a plate of gelatin.", tag: [InsultCategory.WEAKLING]},
    { text: "Have you recovered from arm wrestling that kitten?", tag: [InsultCategory.WEAKLING] },
    { text: "You are a mere shadow of what you should be!", tag: [InsultCategory.WEAKLING, InsultCategory.MONSTER]},
    { text: "You couldn't punch your way out of a soap bubble!", tag: [InsultCategory.WEAKLING, InsultCategory.MONSTER] },
    
    // VILLAIN insults
    { text: "You are as popular as a Pyromancer in a library!", tag: [InsultCategory.VILLAIN] },
    { text: "You black-hearted scoundrel! Evil flows through your veins!", tag: [InsultCategory.VILLAIN] },
    { text: "Thou art a most villainous and treacherous cur!", tag: [InsultCategory.VILLAIN] },
    { text: "Your soul is blacker than a moonless night!", tag: [InsultCategory.VILLAIN] },
    { text: "You're more twisted than a pretzel factory explosion!", tag: [InsultCategory.VILLAIN] },
    { text: "Your heart is colder than a witch's cauldron!", tag: [InsultCategory.VILLAIN] },
    { text: "You make demons look like choir boys!", tag: [InsultCategory.VILLAIN] },
    { text: "Your wickedness knows no bounds, you fiend!", tag: [InsultCategory.VILLAIN] },
    { text: "You're so evil, you make villains look like saints!", tag: [InsultCategory.VILLAIN] },
    { text: "Your malice is matched only by your stupidity!", tag: [InsultCategory.VILLAIN] },
    { text: "You're the reason good people lock their doors at night!", tag: [InsultCategory.VILLAIN] },
    { text: "Tall, Dark, and Despicable!", tag: [InsultCategory.VILLAIN]},
    { text: "I don't know wether to use Charm Person or Speak with Animals!", tag: [InsultCategory.VILLAIN]},
    { text: "Your momma is so ugly, I tried turn undead and she left!", tag: [InsultCategory.VILLAIN]},
    { text: "You ride that horse as poorly as another horse would", tag: [InsultCategory.VILLAIN]},
    { text: "Let me take a wild stab in the dark, which seems to be your entire battle plan", tag: [InsultCategory.VILLAIN]},
    { text: "Your father was so ugly, even the local lich figured she could do better!", tag: [InsultCategory.VILLAIN] },
    { text: "Are you a rogue? Because you stole the joy from my day!", tag: [InsultCategory.VILLAIN, InsultCategory.FOOL] },
    { text: "Do you understand what is about to happen or do you need a diagram?", tag: [InsultCategory.VILLAIN, InsultCategory.FOOL] },
    { text: "No one. Not living, dead, or undead, has ever been glad to see you!", tag: [InsultCategory.VILLAIN, InsultCategory.FOOL]},
    { text: "We found you by casting detect stupid!", tag: [InsultCategory.VILLAIN, InsultCategory.FOOL] },
    { text: "One day you will see the truth of yourself, then you can be just as disappointed in yourself as I am!", tag: [InsultCategory.VILLAIN, InsultCategory.COWARD] },
    { text: "You're the reason they put instructions on health potions!", tag: [InsultCategory.VILLAIN, InsultCategory.FOOL]},
    { text: "I'd tell you mother about your demise, but why give her good news?", tag: [InsultCategory.VILLAIN, InsultCategory.WEAKLING] },
    { text: "What reward could possibly be worth dealing with you?", tag: [InsultCategory.VILLAIN, InsultCategory.FOOL, InsultCategory.MONSTER]},
    { text: "Your parentage is proof while the Animal Friendship spell should be banned!", tag: [InsultCategory.VILLAIN, InsultCategory.WEAKLING] },
    { text: "Save your excuses for your disappointed parents!", tag: [InsultCategory.VILLAIN, InsultCategory.FOOL] },
    { text: "Why do I hear Benny Hill music every time I see you?", tag: [InsultCategory.VILLAIN, InsultCategory.COWARD] },
    { text: "I admit we doubted you and you have contiously lived down to our expectations!", tag: [InsultCategory.VILLAIN, InsultCategory.FOOL] },
    { text: "I could have been your father, but there was a prettier hooker next to your mother!", tag: [InsultCategory.VILLAIN, InsultCategory.NSFW] },
    { text: "You sure you want to do this? Have a younger sibling or small child that could provide us with a greater challenge?", tag: [InsultCategory.VILLAIN, InsultCategory.WEAKLING, InsultCategory.MONSTER]},
    { text: "Is that your war face or did you eat a lemon?", tag: [InsultCategory.VILLAIN, InsultCategory.FOOL]},
    { text: "Have you considered donating your weapons to someone who knows how to use them?", tag: [InsultCategory.VILLAIN, InsultCategory.WEAKLING]},

    // MONSTER insults
    { text: "You monstrous abomination! Even the void fears your existence!", tag: [InsultCategory.MONSTER] },
    { text: "Thou art a foul creature, unfit for the light of day!", tag: [InsultCategory.MONSTER] },
    { text: "Your very presence is an affront to all that is good!", tag: [InsultCategory.MONSTER] },
    { text: "You're so hideous, even mirrors refuse to reflect your image!", tag: [InsultCategory.MONSTER] },
    { text: "Your roar is more like a sickly wheeze!", tag: [InsultCategory.MONSTER] },
    { text: "I've smelled Goblin corpses that were more pleasant than you!", tag: [InsultCategory.MONSTER] },
    { text: "I will tan your skin for my lioncloth!", tag: [InsultCategory.MONSTER]},
    { text: "You look like you were stitched together by a blind Goblin!", tag: [InsultCategory.MONSTER] },
    { text: "I've seen ghosts with more substance than you!", tag: [InsultCategory.MONSTER] },
    { text: "Given your looks, have you considered casting Polymorph on yourself?", tag: [InsultCategory.MONSTER] },
    { text: "I wouldn't touch you with Mage Hand!", tag: [InsultCategory.MONSTER] },
    { text: "Your upcoming murder will probably be the most attention anyone has ever given you", tag: [InsultCategory.MONSTER]},
    { text: "If only I had a Disguise Others spell for you", tag: [InsultCategory.MONSTER]},
    { text: "I've seen more muscles on a skeleton", tag: [InsultCategory.MONSTER]},
    { text: "A body like that could have only been made with the aid of the Darkness spell", tag: [InsultCategory.MONSTER]},
    { text: "You are uglier than a troll's backside!", tag: [InsultCategory.MONSTER]},
    { text: "You look like a bird that swalled a buckler whole", tag: [InsultCategory.MONSTER]},
    { text: "You couldn't get the ground if you jumped", tag: [InsultCategory.MONSTER, InsultCategory.VILLAIN] },
    { text: "I've seen fiercer puppies!", tag: [InsultCategory.MONSTER, InsultCategory.COWARD, InsultCategory.WEAKLING]},
    { text: "Have you ever considered just not breathing?", tag: [InsultCategory.MONSTER, InsultCategory.NSFW]},
    { text: "I can't tell if you are fighting or flailing!", tag: [InsultCategory.MONSTER, InsultCategory.WEAKLING]},
    { text: "You are as welcome as a demon in a church!", tag: [InsultCategory.MONSTER, InsultCategory.VILLAIN]},

    // NSFW insults
    { text: "Between you and Syphilis, at least I could claim a good time before Syphilis showed up", tag:[InsultCategory.NSFW]},
    { text: "You are as worthwhile as a blojob from a Mimic!", tag: [InsultCategory.NSFW] },
    { text: "You mother lied about dropping you. I was a repeated slam", tag: [InsultCategory.NSFW] },
    { text: "You look like you were personally shit out by Shame itself.", tag: [InsultCategory.NSFW]},
    { text: "Please find a mimic and stick your head in it", tag: [InsultCategory.NSFW]},
    { text: "I've drawn a map of all the places you can fuck off to", tag: [InsultCategory.NSFW]},
    { text: "I've seen laterines less full of shit than you", tag: [InsultCategory.NSFW]},
    { text: "How could you possible hope to reproduce with that face and that dick!", tag: [InsultCategory.NSFW]},
    { text: "Have you considered improving your looks with acid?", tag: [InsultCategory.NSFW]},
    { text: "You should stop talking and rest your asshole", tag: [InsultCategory.NSFW] },
    { text: "Your face is proof against a loving god!", tag: [InsultCategory.NSFW, InsultCategory.VILLAIN]},
    { text: "Your face makes me wish for the comfort of blindness!", tag: [InsultCategory.NSFW, InsultCategory.VILLAIN] },
    { text: "You couldn't catch shit dressed as toilet paper.", tag: [InsultCategory.NSFW, InsultCategory.VILLAIN]},

    // Mixed category insults (sorted by first tag in enum order)
    { text: "Looks like my time of not taking you seriously is coming to a crescendo!", tag:[InsultCategory.VILLAIN, InsultCategory.LIAR]}
  ]

export const GetInsultByTag = (tag: InsultCategory): Insult | undefined => {
  const insults = InsultsRepo.filter(insult => insult.tag.includes(tag));
  return insults.length > 0 ? insults[Math.floor(Math.random() * insults.length)] as Insult : undefined;
}
