
export enum InsultCategory {
  COWARD = "coward",
  FOOL = "fool",
  LIAR = "liar",
  WEAKLING = "weakling",
  VILLAIN = "villain",
  MONSTER = "monster",
  NSFW = "nsfw"
}

export type Insult = { tag: Array<InsultCategory>; text: string }

export const InsultsRepo: Array<Insult> = [
    { text: "You yellow-bellied cur! Your spine is made of jelly!", tag: [InsultCategory.COWARD] },
    { text: "Thou art a craven wretch who flees at shadows!", tag: [InsultCategory.COWARD] },
    { text: "You couldn't face a sleeping kitten without trembling!", tag: [InsultCategory.COWARD, InsultCategory.MONSTER] },
    { text: "Face me, you mere stepping stone to my glory!", tag: [InsultCategory.COWARD, InsultCategory.MONSTER, InsultCategory.VILLAIN] },
    { text: "Your courage is as absent as your common sense!", tag: [InsultCategory.COWARD] },
    { text: "You're more chicken than a henhouse full of roosters!", tag: [InsultCategory.COWARD] },
    { text: "Even a frightened rabbit shows more bravery than you!", tag: [InsultCategory.COWARD] },
    { text: "You'd run from your own reflection if it looked threatening!", tag: [InsultCategory.COWARD] },
    { text: "Your backbone must be made of overcooked spaghetti!", tag: [InsultCategory.COWARD] },
    { text: "You're so cowardly, you apologize to doors before opening them!", tag: [InsultCategory.COWARD] },
    { text: "A wet paper bag could intimidate you into submission!", tag: [InsultCategory.COWARD] },
    { text: "You witless buffoon! Your brain is smoother than a bowling ball!", tag: [InsultCategory.FOOL] },
    { text: "Thou art a most addled-pated nincompoop!", tag: [InsultCategory.FOOL] },
    { text: "Your intelligence only rivals that of a particularly dim rock!", tag: [InsultCategory.FOOL] },
    { text: "You couldn't find your way out of a paper bag with a map and GPS!", tag: [InsultCategory.FOOL] },
    { text: "Your head is emptier than a politician's promises!", tag: [InsultCategory.FOOL] },
    { text: "You're about as sharp as a marble!", tag: [InsultCategory.FOOL] },
    { text: "If brains were gunpowder, you couldn't blow your nose!", tag: [InsultCategory.FOOL] },
    { text: "You make a goldfish look like a genius!", tag: [InsultCategory.FOOL] },
    { text: "Your thought process moves slower than continental drift!", tag: [InsultCategory.FOOL] },
    { text: "You're living proof that evolution can go in reverse!", tag: [InsultCategory.FOOL] },
    { text: "You silver-tongued serpent! Truth flees from your lips!", tag: [InsultCategory.LIAR] },
    { text: "Thou art a most perjured and false-hearted knave!", tag: [InsultCategory.LIAR] },
    { text: "Your words are worth less than fool's gold!", tag: [InsultCategory.LIAR] },
    { text: "You couldn't tell the truth if your life depended on it!", tag: [InsultCategory.LIAR] },
    { text: "Your nose should be longer than Pinocchio's by now!", tag: [InsultCategory.LIAR] },
    { text: "You spin tales like a spider spins webs - all lies!", tag: [InsultCategory.LIAR] },
    { text: "Your honesty is as rare as a unicorn in a stable!", tag: [InsultCategory.LIAR] },
    { text: "You'd lie about the color of the sky on a clear day!", tag: [InsultCategory.LIAR] },
    { text: "Your tongue is forked like the serpent you are!", tag: [InsultCategory.LIAR] },
    { text: "Truth and you are strangers who've never been introduced!", tag: [InsultCategory.LIAR] },
    { text: "You feeble-armed milksop! A butterfly could overpower you!", tag: [InsultCategory.WEAKLING] },
    { text: "Thou art weaker than watered-down ale!", tag: [InsultCategory.WEAKLING] },
    { text: "Your muscles have the strength of overcooked noodles!", tag: [InsultCategory.WEAKLING] },
    { text: "You couldn't lift a feather without straining yourself!", tag: [InsultCategory.WEAKLING] },
    { text: "Your arms are more decorative than functional!", tag: [InsultCategory.WEAKLING] },
    { text: "A gentle breeze could knock you over!", tag: [InsultCategory.WEAKLING] },
    { text: "You make a newborn kitten look mighty!", tag: [InsultCategory.WEAKLING] },
    { text: "Your grip is weaker than a politician's handshake!", tag: [InsultCategory.WEAKLING] },
    { text: "You couldn't punch your way out of a soap bubble!", tag: [InsultCategory.WEAKLING, InsultCategory.MONSTER] },
    { text: "Your strength is as impressive as a wilted flower!", tag: [InsultCategory.WEAKLING] },
    { text: "You black-hearted scoundrel! Evil flows through your veins!", tag: [InsultCategory.VILLAIN] },
    { text: "Thou art a most villainous and treacherous cur!", tag: [InsultCategory.VILLAIN] },
    { text: "Your soul is blacker than a moonless night!", tag: [InsultCategory.VILLAIN] },
    { text: "You're more twisted than a pretzel factory explosion!", tag: [InsultCategory.VILLAIN] },
    { text: "Your heart is colder than a witch's cauldron!", tag: [InsultCategory.VILLAIN] },
    { text: "You make demons look like choir boys!", tag: [InsultCategory.VILLAIN] },
    { text: "Your wickedness knows no bounds, you fiend!", tag: [InsultCategory.VILLAIN] },
    { text: "You're so evil, you make villains look like saints!", tag: [InsultCategory.VILLAIN] },
    { text: "Your malice is matched only by your stupidity!", tag: [InsultCategory.VILLAIN] },
    { text: "You're the reason good people lock their doors at night!", tag: [InsultCategory.VILLAIN] },
    { text: "You monstrous abomination! Even the void fears your existence!", tag: [InsultCategory.MONSTER] },
    { text: "Thou art a foul creature, unfit for the light of day!", tag: [InsultCategory.MONSTER] },
    { text: "Your very presence is an affront to all that is good!", tag: [InsultCategory.MONSTER] },
    { text: "You're so hideous, even mirrors refuse to reflect your image!", tag: [InsultCategory.MONSTER] },
    { text: "Your roar is more like a sickly wheeze!", tag: [InsultCategory.MONSTER] },
    { text: "I've smelled Goblin corpses that were more pleasant than you!", tag: [InsultCategory.MONSTER] },
    { text: "I will tan your skin for my lioncloth!", tag: [InsultCategory.MONSTER]},
    { text: "Tall, Dark, and Despicable!", tag: [InsultCategory.VILLAIN]},
    { text: "I don't know wether to use Charm Person or Speak with Animals!", tag: [InsultCategory.VILLAIN]},
    { text: "You look like you were personally shit out by Shame itself.", tag: [InsultCategory.NSFW]},
    { text: "Your face is proof against a loving god!", tag: [InsultCategory.NSFW, InsultCategory.VILLAIN]},
    { text: "I've seen fiercer puppies!", tag: [InsultCategory.MONSTER, InsultCategory.COWARD, InsultCategory.WEAKLING]},
    { text: "Looks like my time of not taking you seriously is coming to a crescendo!", tag:[InsultCategory.VILLAIN, InsultCategory.LIAR]},
    { text: "How could you possible hope to reproduce with that face and that dick!", tag: [InsultCategory.NSFW]},
    { text: "Your momma is so ugly, I tried turn undead and she left!", tag: [InsultCategory.VILLAIN]},
    { text: "You're the reason they put instructions on health potions!", tag: [InsultCategory.VILLAIN, InsultCategory.FOOL]},
    { text: "I'd tell you mother about your demise, but why give her good news?", tag: [InsultCategory.VILLAIN, InsultCategory.WEAKLING] },
    { text: "What reward could possibly be worth dealing with you?", tag: [InsultCategory.VILLAIN, InsultCategory.FOOL, InsultCategory.MONSTER]},
    { text: "Your parentage is proof while the Animal Friendship spell should be banned!", tag: [InsultCategory.VILLAIN, InsultCategory.WEAKLING] },
    { text: "I tried mind control on you, but the spell lacked a target!", tag: [InsultCategory.FOOL]},
    { text: "Have you considered improving your looks with acid?", tag: [InsultCategory.NSFW]},
    { text: "Your face makes me wish for the comfort of blindness!", tag: [InsultCategory.NSFW, InsultCategory.VILLAIN] },
    { text: "Your father was so ugly, even the local lich figured she could do better!", tag: [InsultCategory.VILLAIN] },
    { text: "Why do I hear Benny Hill music every time I see you?", tag: [InsultCategory.VILLAIN, InsultCategory.COWARD] },
    { text: "You sure you want to do this? Have a younger sibling or small child that could provide us with a greater challenge?", tag: [InsultCategory.VILLAIN, InsultCategory.WEAKLING, InsultCategory.MONSTER]},
    { text: "If only I had a Disguise Others spell for you", tag: [InsultCategory.MONSTER]},
    { text: "I've seen more muscles on a skeleton", tag: [InsultCategory.MONSTER]},
    { text: "A body like that could have only been made with the aid of the Darkness spell", tag: [InsultCategory.MONSTER]},
    { text: "Have you ever considered just not breathing?", tag: [InsultCategory.MONSTER, InsultCategory.NSFW]},
    { text: "I can't tell if you are fighting or flailing!", tag: [InsultCategory.MONSTER, InsultCategory.WEAKLING]},
    { text: "Is that your war face or did you eat a lemon?", tag: [InsultCategory.VILLAIN, InsultCategory.FOOL]},
    { text: "Have you considered donating your weapons to someone who knows how to use them?", tag: [InsultCategory.VILLAIN, InsultCategory.WEAKLING]}
  ]

export const GetInsultByTag = (tag: InsultCategory): Insult | undefined => {
  const insults = InsultsRepo.filter(insult => insult.tag.includes(tag));
  return insults.length > 0 ? insults[Math.floor(Math.random() * insults.length)] as Insult : undefined;
}