"use client";
import { CommonItemsByCategory } from "./page";

export const commonItems: CommonItemsByCategory = {
  Weapon: [
    { name: "Club", price: 1, currency: "SP" },
    { name: "Dagger", price: 2, currency: "GP" },
    { name: "Greatclub", price: 2, currency: "SP" },
    { name: "Handaxe", price: 5, currency: "GP" },
    { name: "Javelin", price: 5, currency: "SP" },
    { name: "Light Hammer", price: 2, currency: "GP" },
    { name: "Mace", price: 5, currency: "GP" },
    { name: "Quarterstaff", price: 2, currency: "SP" },
    { name: "Sickle", price: 1, currency: "GP" },
    { name: "Spear", price: 1, currency: "GP" },
    { name: "Light Crossbow", price: 25, currency: "GP" },
    { name: "Dart", price: 5, currency: "CP" },
    { name: "Shortbow", price: 25, currency: "GP" },
    { name: "Sling", price: 1, currency: "SP" },
  ],
  MartialWeapon: [
    { name: "Battleaxe", price: 10, currency: "GP" },
    { name: "Flail", price: 10, currency: "GP" },
    { name: "Glaive", price: 20, currency: "GP" },
    { name: "Greataxe", price: 30, currency: "GP" },
    { name: "Greatsword", price: 50, currency: "GP" },
    { name: "Halberd", price: 20, currency: "GP" },
    { name: "Lance", price: 10, currency: "GP" },
    { name: "Longsword", price: 15, currency: "GP" },
    { name: "Maul", price: 10, currency: "GP" },
    { name: "Morningstar", price: 15, currency: "GP" },
    { name: "Pike", price: 5, currency: "GP" },
    { name: "Rapier", price: 25, currency: "GP" },
    { name: "Scimitar", price: 25, currency: "GP" },
    { name: "Shortsword", price: 10, currency: "GP" },
    { name: "Trident", price: 5, currency: "GP" },
    { name: "War Pick", price: 5, currency: "GP" },
    { name: "Warhammer", price: 15, currency: "GP" },
    { name: "Whip", price: 2, currency: "GP" },
    { name: "Blow Gun", price: 10, currency: "GP" },
    { name: "Hand Crossbow", price: 75, currency: "GP" },
    { name: "Heavy Crossbow", price: 50, currency: "GP" },
    { name: "Long Bow", price: 50, currency: "GP" },
    { name: "Net", price: 1, currency: "GP" },
  ],
  Armor: [
    { name: "Padded Armor", price: 5, currency: "GP" },
    { name: "Leather Armor", price: 10, currency: "GP" },
    { name: "Studded Leather", price: 45, currency: "GP" },
    { name: "Hide Armor", price: 10, currency: "GP" },
    { name: "Chain Shirt", price: 50, currency: "GP" },
    { name: "Scale Mail", price: 50, currency: "GP" },
    { name: "Breastplate", price: 400, currency: "GP" },
    { name: "Half Plate", price: 750, currency: "GP" },
    { name: "Ring Mail", price: 30, currency: "GP" },
    { name: "Chain Mail", price: 75, currency: "GP" },
    { name: "Splint Armor", price: 200, currency: "GP" },
    { name: "Plate Armor", price: 1500, currency: "GP" },
    { name: "Shield", price: 10, currency: "GP" },
    { name: "Buckler", price: 5, currency: "GP" },
    { name: "Tower Shield", price: 30, currency: "GP" },
  ],
  Potions: [
    { name: "Potion of Healing", price: 50, currency: "GP" },
    { name: "Potion of Greater Healing", price: 100, currency: "GP" },
    { name: "Potion of Climbing", price: 50, currency: "GP" },
    { name: "Potion of Watchful Rest", price: 50, currency: "GP" },
    { name: "Potion of Poison", price: 100, currency: "GP" }
  ],
  Gear: [
    { name: "Abacus", price: 2, currency: "GP" },
    { name: "Backpack", price: 2, currency: "GP" },
    { name: "Bedroll", price: 1, currency: "GP" },
    { name: "Bell", price: 1, currency: "GP" },
    { name: "Blanket", price: 5, currency: "SP" },
    { name: "Candle", price: 1, currency: "CP" },
    { name: "Chain (10 ft)", price: 5, currency: "GP" },
    { name: "Chalk", price: 1, currency: "CP" },
    { name: "Grappling Hook", price: 2, currency: "GP" },
    { name: "Hammer", price: 1, currency: "CP" },
    { name: "Ladder", price: 1, currency: "SP" },
    { name: "Lock (basic)", price: 10, currency: "GP" },
    { name: "Manacles", price: 2, currency: "GP" },
    { name: "Pole (10ft)", price: 5, currency: "CP" },
    { name: "Rope (50 ft)", price: 2, currency: "GP" },
    { name: "Shovel", price: 2, currency: "GP" },
    { name: "Signal Whistle", price: 5, currency: "CP" },
    { name: "Soap", price: 2, currency: "CP" },
    { name: "Torch", price: 1, currency: "CP" },
    { name: "Lantern", price: 5, currency: "GP" },
    { name: "Oil Flask", price: 1, currency: "SP" },
    { name: "Rations (1 day)", price: 2, currency: "SP" },
    { name: "Waterskin", price: 2, currency: "GP" },
    { name: "Thieves' Tools", price: 25, currency: "GP" },
  ],
  Scroll: [
    { name: "Scroll of Fireball", price: 150, currency: "GP" },
    { name: "Scroll of Healing", price: 75, currency: "GP" },
    { name: "Scroll of Magic Missile", price: 50, currency: "GP" },
    { name: "Scroll of Shield", price: 25, currency: "GP" },
    { name: "Scroll of Identify", price: 100, currency: "GP" },
    { name: "Scroll of Light", price: 10, currency: "GP" },
    { name: "Scroll of Teleport", price: 500, currency: "GP" },
    { name: "Scroll of Dispel Magic", price: 300, currency: "GP" },
    { name: "Scroll of Invisibility", price: 200, currency: "GP" },
    { name: "Scroll of Lightning Bolt", price: 175, currency: "GP" },
  ],
  Misc: [
    { name: "Gemstone", price: 100, currency: "GP" },
    { name: "Silver Ring", price: 25, currency: "GP" },
    { name: "Gold Necklace", price: 150, currency: "GP" },
    { name: "Ancient Coin", price: 50, currency: "GP" },
    { name: "Crystal Orb", price: 300, currency: "GP" },
    { name: "Mysterious Key", price: 10, currency: "GP" },
    { name: "Spell Component Pouch", price: 25, currency: "GP" },
    { name: "Holy Symbol", price: 5, currency: "GP" },
    { name: "Magnifying Glass", price: 100, currency: "GP" },
    { name: "Music Box", price: 75, currency: "GP" },
  ],
};
