import { Package, Dice6, BookOpen, MapPin, Scroll } from "lucide-react"

export const applications = [
  {
    id: "shopkeeper",
    title: "Dungeon & Shopkeeps",
    description: "Create beautiful fantasy shop inventories with themed layouts and item management",
    icon: Package,
    color: "amber",
    demoLink: "/shopkeeper",
    features: ["5 Fantasy Themes", "Item Categories", "Print Ready"],
  },
  {
    id: "stat-generator",
    title: "Dungeon Coach Stat Generation",
    description: "Generate D&D ability scores using the 4d6 drop lowest method with point allocation tracking",
    icon: Dice6,
    color: "emerald",
    demoLink: "/stat-generator",
    features: ["4d6 Drop Lowest", "Point Budget", "Ability Assignment"],
  },
  {
    id: "character-builder",
    title: "Character Builder",
    description: "Build complete D&D characters with stats, equipment, and background",
    icon: Dice6,
    color: "blue",
    demoLink: "#",
    features: ["Multiple Systems", "Stat Tracking", "Equipment Lists"],
    comingSoon: true,
  },
  {
    id: "npc-cards",
    title: "NPC Cards",
    description:
      "Organize your NPCs and print summary cards that you can reference as part of your DM deck or behind a Gamemaster screen",
    icon: BookOpen,
    color: "purple",
    demoLink: "#",
    features: ["NPC Stats", "Inventory Customization", "Vocal Notes"],
    comingSoon: true,
  },
  {
    id: "map-maker",
    title: "Realm Mapper",
    description: "Design interactive maps for your fantasy worlds and adventures",
    icon: MapPin,
    color: "blue",
    demoLink: "#",
    features: ["Interactive Maps", "Custom Markers", "Layer System"],
    comingSoon: true,
  },
  {
    id: "dice-roller",
    title: "Dice Sanctum",
    description: "Advanced dice rolling with custom formulas and probability analysis",
    icon: Dice6,
    color: "red",
    demoLink: "#",
    features: ["Custom Formulas", "Roll History", "Probability Stats"],
    comingSoon: true,
  },
  {
    id: "lore-keeper",
    title: "Lore Keeper",
    description: "Document and organize your world's history, NPCs, and locations",
    icon: Scroll,
    color: "stone",
    demoLink: "#",
    features: ["World Building", "NPC Database", "Timeline Tracking"],
    comingSoon: true,
  },
]
